# Generated by Django 4.2 on 2025-11-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionasistencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
