# Generated by Django 4.2 on 2025-10-15 04:11

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddeportiva',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('COMPETENCIA', 'Competencia'), ('EVENTO', 'Evento'), ('OTRO', 'Otro')], default='ENTRENAMIENTO'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nombre',
            field=django_mysql.models.EnumField(choices=[('FUTBOL', 'Fútbol'), ('BASQUETBOL', 'Básquetbol'), ('VOLEIBOL', 'Vóleibol'), ('ATLETISMO', 'Atletismo')], default='FUTBOL', unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=django_mysql.models.EnumField(choices=[('8°', 'Básico'), ('1°', 'Primero'), ('2°', 'Segundo'), ('3°', 'Tercero'), ('4°', 'Cuarto')], default='8°'),
        ),
    ]
