# Generated by Django 4.2 on 2025-10-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividaddeportiva',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_hora_marcaje']},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['perfil__user__username']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='rendimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='run',
            field=models.CharField(max_length=20, unique=True, verbose_name='RUN/DNI'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('BAJA', 'Baja'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=12)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='app.disciplina')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='app.estudiante')),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'disciplina')},
            },
        ),
    ]
