# Generated by Django 4.2 on 2025-11-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sesionasistencia_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='app.actividaddeportiva')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
            ],
            options={
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
