# Generated by Django 4.2 on 2025-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_participanteactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividaddeportiva',
            options={},
        ),
        migrations.AddField(
            model_name='actividaddeportiva',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='app.estudiante'),
        ),
        migrations.AddField(
            model_name='actividaddeportiva',
            name='tipo',
            field=models.CharField(choices=[('PARTIDO', 'Partido'), ('TORNEO', 'Torneo')], default='PARTIDO', max_length=10),
        ),
    ]
