# Generated by Django 4.2 on 2025-11-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_actividaddeportiva_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividaddeportiva',
            old_name='alumnos',
            new_name='estudiantes',
        ),
        migrations.AlterField(
            model_name='actividaddeportiva',
            name='tipo',
            field=models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('PARTIDO', 'Partido'), ('TORNEO', 'Torneo')], default='ENTRENAMIENTO', max_length=20),
        ),
    ]
