# Generated by Django 4.2 on 2025-11-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_alumnos_actividaddeportiva_estudiantes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividaddeportiva',
            options={'ordering': ['-fecha_inicio']},
        ),
    ]
