# Generated by Django 4.2 on 2025-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_actividaddeportiva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddeportiva',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('torneo', 'Torneo')], default='normal', max_length=10),
        ),
    ]
