# Generated by Django 4.2 on 2025-10-16 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre de usuario solo puede contener letras, espacios o guiones.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s-]+$')]),
        ),
    ]
