# Generated by Django 4.2 on 2025-10-16 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='La contraseña debe tener al menos una letra mayúscula y una minúscula.', regex='^(?=.*[A-Z])(?=.*[a-z]).*$')]),
        ),
    ]
