# Generated by Django 4.2 on 2025-10-17 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(message='La contraseña debe tener al menos una letra mayúscula y una minúscula.', regex='^(?=.*[A-Z])(?=.*[a-z]).*$')]),
        ),
    ]
